[workspace]
resolver = "3"
members = [
    "netlist",
    "pattern",
    "generic",
    "yosys_json",
    "cli",
]

[workspace.dependencies]
prjunnamed-netlist.path = "netlist"
prjunnamed-pattern.path = "pattern"
prjunnamed-generic.path = "generic"
prjunnamed-yosys_json.path = "yosys_json"
argparse = "0.2"
json = "0.12"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/prjunnamed/prjunnamed"
authors = []
