[package]
name = "prjunnamed-smt2"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
prjunnamed-netlist.workspace = true
env_logger.workspace = true
easy-smt.workspace = true
